/* Autogenerated by png2wx.pl on Tue Jun 27 16:04:26 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_autopilot;
extern wxBitmap *_img_autopilot_pi;

#endif /* ICONS_H */
